### ISSUE TITLE
Extract multiple footnotes

### ISSUE THREAD

**Issue by geo-systems** [morungos/node-word-extractor#16]
Hi there,

Great library - I've been looking for something similar for quite a while!

I tried to extract text from a file with multiple footnotes. Unfortunately, the `getFootnotes` method only returns the first one :(

Any ideas how to work around that?

**Comment by morungos** [comment]
Can you try `getFootnotes(false)` to turn off filtering? I'm wondering whether that's what's caused an issue. The entire footnote block is supposed to be returned, but there could be something wrong there. 

If that's not enough, I'll add a test and see what I can do.

**Comment by geo-systems** [comment]
Thanks, unfortunately that did not help.

To reproduce the issue, I've taken this sample docx file (https://calibre-ebook.com/downloads/demos/demo.docx). I opened it MS Word and saved it as a `Word 97-2004 Document (.doc)` file.

The first footnote is returned, however the second endnote is not returned by any of the methods ...

**Comment by morungos** [comment]
Ah, looking at the sample, the second one is an endnote, not a footnote, and it never occurred to me that MS Word would handle the two differently at the file level. But it looks like it does. (Right clicking shows a "Convert to footnote" which, if you use it, might suddenly make the data work after a save.) I think endnotes might post-date when I first started my work on Word extraction modules.

I think that's maybe the issue. I am guessing you really want endnotes to be exposed as well as footnotes. Does that make sense? It's not a huge task, as far as I can tell.

**Comment by geo-systems** [comment]
Oh I see - I also didn't know they're different.

I would like the endnotes exposed via some method. It doesn't need need to be `getFootnotes` ... Is there any method that exposes that? If not, I'm happy to use a new method (e.g. `getEndnotes`).

Kindly let me know what are the options?

**Comment by morungos** [comment]
Okay, I added a new method, `getEndnotes()` and it should behave identically to `getFootnotes()`. It's pushed in 0.2.1. That should fix it for you -- there's a test which confirms the differences. 

If that doesn't help, let me know and I'll re-open.

**Comment by morungos** [comment]
And now I think on it, we should probably also handle textboxes and some of the other new beasties that MS added.

**Comment by geo-systems** [comment]
Fantastic - the fix works like a charm :) 

I'll keep testing with other sample docs and let you know.
