### ISSUE TITLE
special character issue

### ISSUE THREAD

**Issue by deepdil-sp** [morungos/node-word-extractor#21]
special characters like - , ",  spa pu2 like that

**Comment by morungos** [comment]
Yes, that's an issue. I did build a translation set for characters like that, but I don't think it really made it into the API anywhere, so I'll make sure that's handled soon. The intention is that Word characters get mapped into Unicode equivalents when I can. There might be some weird cases with certain Windows codepages that are a bigger challenge, so if it's a file that still causes issues, I might need a sample to add to the test cases, if you can make a small file that exemplifies the problems.

**Comment by morungos** [comment]
This is significantly improved in 5a6481fa. This version uses a more agnostic document format, and filters data before it is stored. Now, all data internally is a Word Unicode. We have an optional cleaning on the output, which manages a few replacements. If you want to do better, you'll need to do something yourself, but this should give you more or less clean Unicode to work with.
