### ISSUE TITLE
Error: Not a valid compound document

### ISSUE THREAD

**Issue by PrasannaBrabourame** [morungos/node-word-extractor#22]
When uploading a document system is showing error as "Error: Not a valid compound document". same document is parsing mammoth.

**Comment by JamesGu14** [comment]
same here, I uploaded a docx file, is this the cause?

**Comment by aprilmintacpineda** [comment]
Yeah

```js
(async() => {
  const path = require('path');
  const WordExtractor = require('word-extractor');
  const extractor = new WordExtractor();

  const extracted = await extractor.extract(path.join(__dirname, 'template1.docx'));

  console.log(extracted);
})();
```

Throws `UnhandledPromiseRejectionWarning: Error: Not a valid compound document`.

**Comment by aprilmintacpineda** [comment]
Yeah

```js
(async() => {
  const path = require('path');
  const WordExtractor = require('word-extractor');
  const extractor = new WordExtractor();

  const extracted = await extractor.extract(path.join(__dirname, 'template1.docx'));

  console.log(extracted);
})();
```

Throws `UnhandledPromiseRejectionWarning: Error: Not a valid compound document`.

**Comment by Overdrivr** [comment]
Same here. Is this library working ? I've faced this error with the first document I tried.

**Comment by reezon** [comment]
I have try doc and docx files
found it only works with doc
not work with docx

**Comment by morungos** [comment]
Yes, docx is an entirely different format, and it's technically much simpler to extract text from, so I didn't add support for that yet. 

To get the text out of a docx file, you can unzip it (it's actually a zip file!) and then you'll find a bunch of XML files inside, some of which present the content. Embedded images and everything else get packaged in there too. 

That part is relatively straightforward -- what I have had no time to look into, is making the XML extraction consistent with the .doc (OLE-based) formats.

**Comment by rsweetland** [comment]
@morungos thx for the awesome lib, and the tip for the tip on docx format. I was able to get by with [docx-parser](https://www.npmjs.com/package/docx-parser) for now, but prefer your license. Seems like an opportunity for contributors to your lib : )

**Comment by john-aws** [comment]
Related: https://github.com/morungos/node-word-extractor/pull/28
