### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by infFenrir** [morungos/node-word-extractor#23]
Node 9 - 12
Windows 10

Thanks for the wonderful library :)

File descriptors do not close...
I even downloaded ProcessExplorer to make sure of this :(
It turns out to open somewhere 8000 - 8200 files before the fall -> Error: EMFILE: too many open files

```
const fs = require('fs')
const path = require('path')
const WordExtractor = require('word-extractor')

let extractor = new WordExtractor()

const foo = async (pathDir) => {
  let arrFileName = fs.readdirSync(pathDir)
   let count = 0

  for (let fileName of arrFileName) {
    let pathFile = path.join(pathDir, fileName)
    let res = await extractor.extract(pathFile)
    let doc = res.getBody()
    count = count + 1
    console.log(count)
  }
}
foo('d:/Dir')
```
Help me, pleath

**Comment by InfSpell** [comment]
This does not work for me, I tried both use `Promise.all` and even 
`arr.reduce((p, f) => p.then(f), Promise.resolve())`
still getting an error
-> EMFILE: too many open files, open :(((

**Comment by morungos** [comment]
Um, yeah! That's not good. There is not always a call to `fs.close()`, so that's fairly obviously wrong. This is a real bug and it deserves close attention.
