### ISSUE TITLE
Data is a promise, cant make it in a var - async await not working at all

### ISSUE THREAD

**Issue by JanneJanso** [morungos/node-word-extractor#24]

**Comment by reezon** [comment]
you could write it like this:

```
var extractor = new WordExtractor();
        var extracted = extractor.extract(appRoot + '/temp/' + body.file_name);
        extracted.then(async function(doc) {
          // console.log(doc.getBody());
          await xxxx
        })
```

**Comment by Elvanos** [comment]
`
const outputText = await new Promise(resolve => {
        const extractor = new WordExtractor()
        const extracted = extractor.extract(enterPath)
        extracted.then(function(doc) {
          resolve(doc.getBody())
        })
      })
`

@JanneJanso you are welcome. Had the same issue with my code.

**Comment by morungos** [comment]
Thanks for documenting, this -- I'm still not amazingly up to speed with async and await yet. However, as I understand it, async and await are basically sugar for promises, so, in theory, in an async function...

```
async function getMyText(file) {
  const extractor = new WordExtractor();
  const doc = await extractor.extract(file);
  console.log(doc.getBody());
}
```
