### ISSUE TITLE
Is this cross-platform ?

### ISSUE THREAD

**Issue by Overdrivr** [morungos/node-word-extractor#25]
I see in this ticket https://github.com/morungos/node-word-extractor/issues/11 a mention of the OLE implementation, is this package actually using Word itself to parse the documents ?

Basically, my question is, is this package really pure-JS no-binary-dependency and cross platform ?

**Comment by morungos** [comment]
Yes, it's very much cross-platform. I thought I'd been clear enough about that in the `README.md`, but now I read it from someone else's point of view, I can see that it isn't clear as it should be. I'll update the documentation accordingly. And thanks.
