### ISSUE TITLE
Add a way to read macros

### ISSUE THREAD

**Issue by serkonda7** [morungos/node-word-extractor#47]
Read the `vbaProject.bin` and get the content as readable text.

**Comment by morungos** [comment]
Pull requests are always welcome, but my aim with this was always to access the human-useful text, admittedly that's a challenge with some of the styling being very relevant to it.

If you want the VB code specifically, maybe the [olevba tool](https://www.decalage.info/en/vba_tools) will do a better job for you. Certainly for OOXML files, there are much simpler ways to get the VB code, but these tools seem to support both OLE and OOXML files.

So I'm not planning on doing this, but let me know if you have something that's more closely linked to the human text.
