### ISSUE TITLE
Fix the docs so that returned doc is actually a promise

### ISSUE THREAD

**Issue by SHocker-Yu** [morungos/node-word-extractor#6]
## hi,im using this package for a test,and i got this problem

`F:\parseWord\app.js:4
var body = doc.getBody();
               ^

TypeError: doc.getBody is not a function
    at Object.<anonymous> (F:\parseWord\app.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`
## code:

`var WordExtractor = require("word-extractor");
var extractor = new WordExtractor();
var doc = extractor.extract("./testDocccccc.doc")
var body = doc.getBody();

console.log(body)`

**Comment by morungos** [comment]
Do you have a test/public version of this .doc file you could share with me, then I can take a look? You send directly to stuart@morungos.com if you prefer.

**Comment by SHocker-Yu** [comment]
thank you! i have sent two mails to you,the second one is my project.

**Comment by morungos** [comment]
Got the file. This is... interesting. I'm not getting the same error, and I am getting text out which visually matches the document. But there's some weird character-level stuff there too, which broke a test or two. So I'm going to dig at it.

What version of Node.js are you using? I'm suspicious there might be a Unicode type issue at play, and that has changed a bit across versions. 

Haven't tried Windows yet, as that might be a factor too. I'll check that tomorrow.

**Comment by SHocker-Yu** [comment]
OS:win 10
node:v4.4.7
the file contains chinese,it may the reason of the weird character-level stuff.
thank you ,good night.

**Comment by morungos** [comment]
Ah, OK. I think this is a *major* documentation error. As far as I can tell, the `WordExtractor#extract` method returns a *promise that resolves to a document*, rather than a document. 

I can't see how I didn't document this in the README.md (which I clearly didn't), because it looks like it was always this way, and the unit tests certainly work that way. 

However, it does make sense, as otherwise it'd be blocking on I/O, and that's not good. 

So try something along the lines of...

```
var WordExtractor = require("word-extractor");
var extractor = new WordExtractor();
var pd = extractor.extract("./testDocccccc.doc");
pd.then(function(doc) {
  console.log(doc.getBody);
});
```

Can you see if this works for you, and if so I'll amend the docs. The test files are a good place to look for examples, although `expect` obfuscates it a little. 

And I'm truly sorry.

**Comment by SHocker-Yu** [comment]
I'm sorry for replying you so late,we have a meeting all day.it is a good news for what you find.
i did the test just now,
and  ''console.log(doc.getBody());''  missing brackets after getBody.
console output: This is a test for parsing the Word file in node.
sure,it works.
but the chinese in the files can't read successfully,my true files are all in chinese,could you help for that?
whatever,thank you very much!

**Comment by SHocker-Yu** [comment]
Ah,it works for chinese,but there are something interesting.
The examples:
wait a monment

**Comment by morungos** [comment]
Good for finding this. If you can make enough of a test case that I can get it, I'd be happy to look into this. It's very possible, given that the encodings used inside both Word and JavaScript are neither especially standard, and there could well be issues that have fallen in between. 

I'd be happy to fix if you can find a small enough test file that I can understand, although it might be best flagging that as a new issue, and I'll use this to fix the docs
