### ISSUE TITLE
Cannot read properties of null (reading 'open') while using Uint8Array as params for extract method.

### ISSUE THREAD

**Issue by weponary** [morungos/node-word-extractor#64]
If i pass Uint8Array data in below function like in example below
       
        const extracted = await extractor.extract(data);
        
        
        I got this error 
        
        error TypeError: Cannot read properties of null (reading 'open')

**Comment by camrun91** [comment]
I am having this same issue.

**Comment by weponary** [comment]
Hi @camrun91, It was the type error. 
You need to pass the buffer instead of Uint8Array. 
You can pull the latest TS version and it will work fine.
