### ISSUE TITLE
Does not extract Table data

### ISSUE THREAD

**Issue by mouryaamit** [morungos/node-word-extractor#9]

**Comment by morungos** [comment]
Not sure about this, as I couldn't replicate it perfectly. Table cell data was there when I tested, but the delimiter substitution was broken which might have concealed it. They should now be tabs, in a new version `0.1.4` (just published). If that doesn't work (and there are some weird corners in Word for nested tables) then if you can attach a broken sample and re-open. 

Row boundaries are a bit hard in Word, and I haven't engaged with that yet, either. If you need them, re-open the issue on that, again, a test file would be helpful.
